objective:
  - Sparse Support Recovery

dataset: # dataset to run benchmark on
  - simulated[n_samples=10,n_features=50,density=0.05,rho=0.3]

solver: # list of example solvers to do benchmark
  - celer[0.9,0.5,0.1]
  - fista[reg=[0.9,0.5,0.1],use_acceleration=True]

# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 20
